include(${CMAKE_CURRENT_LIST_DIR}/../check.cmake)
function(Process)
    PrepareDep(1.47.0)
    DownloadDep(TAG v${_DEP_VER} SPEED_UP_FILE ${_DEP_NAME}-${_DEP_VER}.tar.gz)
    Ninja(ARGS -DgRPC_INSTALL=ON -DgRPC_BUILD_TESTS=OFF)
    PostProcess()
endfunction(Process)
Process()
ProcessAddLibrary()